name: Doctore CI/CD

on:
  push:
    branches:
      - doctore-source-patch-3
  pull_request:
    branches:
      - doctore-source-patch-3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest --maxfail=5 --disable-warnings

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit Application
      run: |
        nohup streamlit run doctore_dashboard.py --server.port 8501 --server.address 0.0.0.0 > dashboard_log.out 2>&1 &